name: cpp-ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake --preset debug
      - name: Build
        run: cmake --build --preset debug
      - name: Test
        run: ctest --preset debug

